services:
  api:
    build: .                # utilise le Dockerfile du dossier courant
    ports:
      - "8000:8000"          # host:container -> accessible via 127.0.0.1:8000
    environment:
      # "db" = nom du service Postgres ci-dessous, résolu automatiquement par Compose
      DATABASE_URL: ${DATABASE_URL} #DockerCompose va lire directemtn le .env qui est dans la racine avec lui
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db                  # démarre db avant api (mais n'attend pas qu'il soit "prêt")

  db:
    image: postgres:16       # image officielle, pas besoin de Dockerfile custom
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}   # ces 3 vars = init automatique de la base au 1er démarrage
    ports:
      - "5432:5432"          # optionnel : permet de se connecter depuis un client hors Docker (ex. DBeaver)
    volumes:
      - pgdata:/var/lib/postgresql/data   # données persistées hors du container

volumes:
  pgdata:                    # déclare le volume nommé utilisé ci-dessus

# pour lancer le compose : docker compose up --build
# utiliser  `http://127.0.0.1:8000`
# pour reset totalement la db à la fermeture du docker
# docker compose down -v
# pour accèder au terminal du postgre après lancement du compose:
# `docker compose exec db psql -U ytastyg3 -d ytastyg3`
#  |         Commande	        |            Effet
#  |\dt	                        |liste toutes les tables
#  |\d                          |nom_table	détail des colonnes d'une table (types, contraintes)
#  |SELECT * FROM restaurants;	|voir le contenu d'une table
#  |\q	                        |quitter